
 
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import MainNavbar from './lib/component/utilityCom/MainNavbar'
import { cookies } from 'next/headers'
import PlainNavbar from './lib/component/utilityCom/PlainNavbar'
 

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata= {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}) {
  const cookieStore = await cookies()
  const token = cookieStore.get('token')
 
  return (
    
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="mb-20">
          {
            token ? <PlainNavbar/> : <MainNavbar/>
          }

           
          </div>
          
          {children} 
        </body>
      </html>
 
  )
}